{% set name = "mitmproxy" %}
{% set version = "9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mitmproxy/mitmproxy/archive/{{ version }}.tar.gz
  sha256: 2acd2c16e5bc02cd1dab8c58003254a71a2ee0ec0366001f624f85c980a2b43a

build:
  entry_points:
    - mitmproxy = mitmproxy.tools.main:mitmproxy
    - mitmdump = mitmproxy.tools.main:mitmdump
    - mitmweb = mitmproxy.tools.main:mitmweb
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - asgiref >=3.2.10,<3.6
    - blinker >=1.4,<1.5
    - brotli-python >=1.0,<1.1
    - certifi >=2019.9.11
    - cryptography >=36,<38
    - flask >=1.1.1,<2.2
    - h11 >=0.11,<0.14
    - h2 >=4.1,<5
    - hyperframe >=6.0,<7
    - kaitaistruct >=0.7,<0.10
    - ldap3 >=2.8,<2.10
    - msgpack-python >=1.0.0,<1.1.0
    - passlib >=1.6.5,<1.8
    - protobuf >=3.14,<5
    - publicsuffix2 >=2.20190812,<3
    - pydivert >=2.0.3,<2.2          # [win]
    - pyopenssl >=21.0,<22.1
    - pyparsing >=2.4.2,<3.1
    - pyperclip >=1.6.0,<1.9
    - python
    - ruamel.yaml >=0.16,<0.18
    - sortedcontainers >=2.3,<2.5
    - tornado >=6.1,<7
    - urwid >=2.1.1,<2.2
    - wsproto >=1.0,<1.2
    - zstandard >=0.11,<0.19

test:
  imports:
    - mitmproxy
  commands:
    - pip check
    - mitmproxy --version
    - mitmdump --version
    - mitmweb --version
  requires:
    - pip

about:
  home: http://mitmproxy.org
  summary: An interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers.
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - mitmproxy/tools/web/static/images/chrome-devtools/LICENSE
    - web/src/images/chrome-devtools/LICENSE

extra:
  recipe-maintainers:
    - jonashaag
    - AdrianFreundQC
    - freundTech
